// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: user.proto

package user

import (
	_ "github.com/995933447/microgosuit-skeleton-example/enum"
	_ "github.com/995933447/microgosuit/skeleton/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserReq) Reset() {
	*x = SetUserReq{}
	mi := &file_user_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserReq) ProtoMessage() {}

func (x *SetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserReq.ProtoReflect.Descriptor instead.
func (*SetUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{0}
}

func (x *SetUserReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type SetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetUserResp) Reset() {
	*x = SetUserResp{}
	mi := &file_user_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetUserResp) ProtoMessage() {}

func (x *SetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetUserResp.ProtoReflect.Descriptor instead.
func (*SetUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{1}
}

func (x *SetUserResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type GetUserReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserReq) Reset() {
	*x = GetUserReq{}
	mi := &file_user_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserReq) ProtoMessage() {}

func (x *GetUserReq) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserReq.ProtoReflect.Descriptor instead.
func (*GetUserReq) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{2}
}

func (x *GetUserReq) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetUserResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	User          *GetUserResp_User      `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp) Reset() {
	*x = GetUserResp{}
	mi := &file_user_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp) ProtoMessage() {}

func (x *GetUserResp) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp.ProtoReflect.Descriptor instead.
func (*GetUserResp) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3}
}

func (x *GetUserResp) GetUser() *GetUserResp_User {
	if x != nil {
		return x.User
	}
	return nil
}

type GetUserResp_User struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserResp_User) Reset() {
	*x = GetUserResp_User{}
	mi := &file_user_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserResp_User) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserResp_User) ProtoMessage() {}

func (x *GetUserResp_User) ProtoReflect() protoreflect.Message {
	mi := &file_user_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserResp_User.ProtoReflect.Descriptor instead.
func (*GetUserResp_User) Descriptor() ([]byte, []int) {
	return file_user_proto_rawDescGZIP(), []int{3, 0}
}

func (x *GetUserResp_User) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

var File_user_proto protoreflect.FileDescriptor

const file_user_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"user.proto\x12\x04user\x1a9github.com/995933447/microgosuit/skeleton/proto/ext.proto\x1a\n" +
	"enum.proto\"\x1c\n" +
	"\n" +
	"SetUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"!\n" +
	"\vSetUserResp\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x1c\n" +
	"\n" +
	"GetUserReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"U\n" +
	"\vGetUserResp\x12*\n" +
	"\x04user\x18\x01 \x01(\v2\x16.user.GetUserResp.UserR\x04user\x1a\x1a\n" +
	"\x04User\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name2\xa0\x02\n" +
	"\x04user\x12.\n" +
	"\aGetUser\x12\x10.user.GetUserReq\x1a\x11.user.GetUserResp\x12.\n" +
	"\aSetUser\x12\x10.user.SetUserReq\x1a\x11.user.SetUserResp\x12<\n" +
	"\x13GetUserOutputStream\x12\x10.user.GetUserReq\x1a\x11.user.GetUserResp0\x01\x12;\n" +
	"\x12GetUserInputStream\x12\x10.user.GetUserReq\x1a\x11.user.GetUserResp(\x01\x12=\n" +
	"\x12GetUserInOutStream\x12\x10.user.GetUserReq\x1a\x11.user.GetUserResp(\x010\x012O\n" +
	"\vUserGateway\x12@\n" +
	"\vGetUserInfo\x12\x10.user.GetUserReq\x1a\x11.user.GetUserResp\"\f\x8a\x9d \b\n" +
	"\x04POST\x10\x01B8Z6github.com/995933447/microgosuit-skeleton-example/userb\x06proto3"

var (
	file_user_proto_rawDescOnce sync.Once
	file_user_proto_rawDescData []byte
)

func file_user_proto_rawDescGZIP() []byte {
	file_user_proto_rawDescOnce.Do(func() {
		file_user_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)))
	})
	return file_user_proto_rawDescData
}

var file_user_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_user_proto_goTypes = []any{
	(*SetUserReq)(nil),       // 0: user.SetUserReq
	(*SetUserResp)(nil),      // 1: user.SetUserResp
	(*GetUserReq)(nil),       // 2: user.GetUserReq
	(*GetUserResp)(nil),      // 3: user.GetUserResp
	(*GetUserResp_User)(nil), // 4: user.GetUserResp.User
}
var file_user_proto_depIdxs = []int32{
	4, // 0: user.GetUserResp.user:type_name -> user.GetUserResp.User
	2, // 1: user.user.GetUser:input_type -> user.GetUserReq
	0, // 2: user.user.SetUser:input_type -> user.SetUserReq
	2, // 3: user.user.GetUserOutputStream:input_type -> user.GetUserReq
	2, // 4: user.user.GetUserInputStream:input_type -> user.GetUserReq
	2, // 5: user.user.GetUserInOutStream:input_type -> user.GetUserReq
	2, // 6: user.UserGateway.GetUserInfo:input_type -> user.GetUserReq
	3, // 7: user.user.GetUser:output_type -> user.GetUserResp
	1, // 8: user.user.SetUser:output_type -> user.SetUserResp
	3, // 9: user.user.GetUserOutputStream:output_type -> user.GetUserResp
	3, // 10: user.user.GetUserInputStream:output_type -> user.GetUserResp
	3, // 11: user.user.GetUserInOutStream:output_type -> user.GetUserResp
	3, // 12: user.UserGateway.GetUserInfo:output_type -> user.GetUserResp
	7, // [7:13] is the sub-list for method output_type
	1, // [1:7] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_user_proto_init() }
func file_user_proto_init() {
	if File_user_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_user_proto_rawDesc), len(file_user_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_user_proto_goTypes,
		DependencyIndexes: file_user_proto_depIdxs,
		MessageInfos:      file_user_proto_msgTypes,
	}.Build()
	File_user_proto = out.File
	file_user_proto_goTypes = nil
	file_user_proto_depIdxs = nil
}
