// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.7
// 	protoc        v4.24.2
// source: enum.proto

package enum

import (
	_ "github.com/995933447/microgosuit/skeleton/pb"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type RpcPort int32

const (
	RpcPort_RpcPortNil  RpcPort = 0
	RpcPort_RpcPortUser RpcPort = 9111
)

// Enum value maps for RpcPort.
var (
	RpcPort_name = map[int32]string{
		0:    "RpcPortNil",
		9111: "RpcPortUser",
	}
	RpcPort_value = map[string]int32{
		"RpcPortNil":  0,
		"RpcPortUser": 9111,
	}
)

func (x RpcPort) Enum() *RpcPort {
	p := new(RpcPort)
	*p = x
	return p
}

func (x RpcPort) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (RpcPort) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[0].Descriptor()
}

func (RpcPort) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[0]
}

func (x RpcPort) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use RpcPort.Descriptor instead.
func (RpcPort) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{0}
}

type ErrCode int32

const (
	ErrCode_ErrNil  ErrCode = 0
	ErrCode_ErrFail ErrCode = 1001
)

// Enum value maps for ErrCode.
var (
	ErrCode_name = map[int32]string{
		0:    "ErrNil",
		1001: "ErrFail",
	}
	ErrCode_value = map[string]int32{
		"ErrNil":  0,
		"ErrFail": 1001,
	}
)

func (x ErrCode) Enum() *ErrCode {
	p := new(ErrCode)
	*p = x
	return p
}

func (x ErrCode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ErrCode) Descriptor() protoreflect.EnumDescriptor {
	return file_enum_proto_enumTypes[1].Descriptor()
}

func (ErrCode) Type() protoreflect.EnumType {
	return &file_enum_proto_enumTypes[1]
}

func (x ErrCode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ErrCode.Descriptor instead.
func (ErrCode) EnumDescriptor() ([]byte, []int) {
	return file_enum_proto_rawDescGZIP(), []int{1}
}

var File_enum_proto protoreflect.FileDescriptor

const file_enum_proto_rawDesc = "" +
	"\n" +
	"\n" +
	"enum.proto\x12\x04enum\x1a9github.com/995933447/microgosuit/skeleton/proto/ext.proto*1\n" +
	"\aRpcPort\x12\x0e\n" +
	"\n" +
	"RpcPortNil\x10\x00\x12\x10\n" +
	"\vRpcPortUser\x10\x97G\x1a\x04\x88\x9d \x01*#\n" +
	"\aErrCode\x12\n" +
	"\n" +
	"\x06ErrNil\x10\x00\x12\f\n" +
	"\aErrFail\x10\xe9\aB8Z6github.com/995933447/microgosuit-skeleton-example/enumb\x06proto3"

var (
	file_enum_proto_rawDescOnce sync.Once
	file_enum_proto_rawDescData []byte
)

func file_enum_proto_rawDescGZIP() []byte {
	file_enum_proto_rawDescOnce.Do(func() {
		file_enum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)))
	})
	return file_enum_proto_rawDescData
}

var file_enum_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_enum_proto_goTypes = []any{
	(RpcPort)(0), // 0: enum.RpcPort
	(ErrCode)(0), // 1: enum.ErrCode
}
var file_enum_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_enum_proto_init() }
func file_enum_proto_init() {
	if File_enum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_enum_proto_rawDesc), len(file_enum_proto_rawDesc)),
			NumEnums:      2,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_enum_proto_goTypes,
		DependencyIndexes: file_enum_proto_depIdxs,
		EnumInfos:         file_enum_proto_enumTypes,
	}.Build()
	File_enum_proto = out.File
	file_enum_proto_goTypes = nil
	file_enum_proto_depIdxs = nil
}
