// Code generated by protoc-gen-grpc-server. DO NOT EDIT.
package main

import "github.com/995933447/microgosuit"

func init() {
	microgosuit.SetModuleName("user")
}

var ServiceNames = []string{
	"user.User",
	"user.UserGateway",
}
