// Code generated by protoc-gen-grpc-server. DO NOT EDIT.
package main

import (
	"github.com/995933447/microgosuit/skeleton"
	"github.com/995933447/microgosuit-skeleton-example/enum"
)

var rpcPort = int(enum.RpcPort_RpcPortUser)

func GetListenRpcPort() (int, error) {
	if rpcPort > 0 {
		return rpcPort, nil
	}

	port, err := skeleton.RandomAvailableRpcPort()
	if err != nil {
		return 0, err
	}

	rpcPort = port

	return rpcPort, nil
}
